version: '3.8'

services:
  db:
    image: circleci/postgres:12.9
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: example
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    networks:
      - app_net

  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    ports:
      - target: 9200
        published: 9200
    networks:
      - app_net

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - app_net

  web: &web
    volumes:
      - tmp-dir:/tmp
    depends_on:
      - db
    links:
      - 'db:database'
    ports:
      - '4000:4000'
    networks:
      - app_net
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://johndoe:randompassword@database:5432/example

volumes:
  database-data:
  tmp-dir:
    driver: local
  es_data:
    driver: local

networks:
  app_net:
    driver: bridge
